# Generated by Django 4.1.7 on 2023-03-22 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=100)),
                ('price', models.FloatField(max_length=100)),
                ('link', models.CharField(max_length=100)),
                ('query', models.CharField(max_length=50)),
                ('relevant', models.BooleanField(max_length=50)),
            ],
        ),
    ]
